/// Flutter icons CryptoAppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CryptoAppIcons
///      fonts:
///       - asset: fonts/CryptoAppIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CryptoAppIcons {
  CryptoAppIcons._();

  static const _kFontFam = 'CryptoAppIcons';
  static const String _kFontPkg = null;

  static const IconData down_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forgot_key = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iota = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData litecoin = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin = IconData(0xf15a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
